// Generated by CoffeeScript 1.4.0
(function() {
  var address, replace_ssh_event_handler, retry_rate, setup, ssh_button, username, __;

  __ = Zepto;

  username = 'rightscale';

  address = 'td[data-column_name="Public IP"] a';

  ssh_button = 'a[href*="managed_ssh"]';

  retry_rate = 100;

  setup = function() {
    replace_ssh_event_handler();
    return __('body').on('DOMNodeInserted', function(e) {
      return replace_ssh_event_handler();
    });
  };

  replace_ssh_event_handler = function() {
    var buttons;
    buttons = __(ssh_button);
    if (!buttons.length) {
      return;
    }
    return buttons.each(function(i) {
      var bb, host, index;
      bb = __(this);
      index = bb.attr('href').indexOf('ip_address');
      if (index > 0) {
        host = bb.attr('href').substring(index + 11);
      } else if (!bb.attr('id')) {
        address = 'td[data-column_name="Public IP"] a';
        host = bb.closest('tr').find(address).text().trim();
        if (host === "") {
          address = 'td[data-column_name="Public DNS"] a';
          host = bb.closest('tr').find(address).text().trim();
        }
      } else {
        return;
      }
      bb.attr('href', "ssh://" + username + "@" + host);
      bb.removeAttr('data-popup');
      return bb.removeAttr('data-behaves');
    });
  };

  setup();

}).call(this);
